# Generated by Django 3.0 on 2022-04-27 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220420_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account_no',
        ),
    ]
